#!/bin/sh

stampaOk(){
	echo -e "\e[1;34m[\e[1;32m OK \e[1;34m]\e[0m $1"
}

mount -t proc proc /proc
stampaOk "Montando /proc"
sleep 0.4

mount -t sysfs sysfs /sys
stampaOk "Montando /sys"
sleep 0.4

mount -t devtmpfs devtmpfs /dev
stampaOk "Montando /dev"
sleep 0.4

loadkmap < /usr/share/keymaps/it.bmap
stampaOk "impostanado il layout in italiano"
sleep 0.4


# Cornice Blu Doppia - Calibrata per l'MSI
echo -e "\e[34m\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x97\e[0m"

# Testo interno
echo -e "\e[34m\xe2\x95\x91 \e[1;37m  B I L L Y  O S   \e[0m\e[34m\xe2\x95\x91\e[0m"
echo -e "\e[34m\xe2\x95\x91 \e[34m      v 0.2        \e[0m\e[34m\xe2\x95\x91\e[0m"
echo -e "\e[34m\xe2\x95\x91 \e[1;33m  EFI SUPPORTED    \e[0m\e[34m\xe2\x95\x91\e[0m"

# Chiusura cornice
echo -e "\e[34m\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x9d\e[0m"

echo ""
echo -e "\e[1;34mLive Session\e[0m avviata con successo."
echo -e "Digita \e[1;32mhelp\e[0m per la lista dei comandi disponibili."
echo ""

trap 'echo "spegnimento in corso"; reboot-p' SIGUSR1
trap 'echo "riavviamento in corso"; reboot' SIGUSR2

alias changelog="cat changelog"

export PS1='\[\e[1;34m\]BillyOS \[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;33m\]\w\[\e[0m\]# '

while :; do
	setsid cttyhack /bin/sh < /dev/tty0 > /dev/tty0 2>&1
	echo -e "\e[31mla shell e' stato chiusa o e' crashata :|, riavvio in corso... tra 1 secondo\e[0m"
	sleep 1
done


